services:
  gitea:
    image: docker.gitea.com/gitea:1.23.7-rootless
    container_name: gitea
    env_file:
      - .env
    volumes:
      - ./gitea/data:/var/lib/gitea
      - ./gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
