- name: Launch GitLab container(s) with Docker Compose
  community.docker.docker_compose:
    project_src: "/gitlab"
    pull: false
    state: present
  register: compose_result
  tags: gitlab_docker

- name: Display Docker Compose result
  ansible.builtin.debug:
    msg: >
      GitLab service is {{ compose_result.changed | ternary('(re)started', 'unchanged (already running)') }}.
  tags: gitlab_docker
