- name: Ensure GitLab config/logs/data directories exist
  ansible.builtin.file:
    path: "/gitlab/{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - config
    - logs
    - data
  tags: gitlab_docker

- name: Pull GitLab Docker image (if not already pulled)
  community.docker.docker_image:
    name: "gitlab/gitlab-ce:17.9.0-ce.0"
    source: pull
  register: gitlab_image
  tags: gitlab_docker

- name: Notify image pull result
  ansible.builtin.debug:
    msg: "GitLab image pull: {{ gitlab_image.changed | ternary('Image updated/pulled', 'Image already up-to-date') }}"
  tags: gitlab_docker
