- name: Get initial root password from GitLab container
  ansible.builtin.shell: |
    docker exec gitlab grep 'Password:' /etc/gitlab/initial_root_password
  register: root_password_out
  changed_when: false
  tags: gitlab_post

- name: Show initial root password
  ansible.builtin.debug:
    msg: "GitLab initial root password: {{ root_password_out.stdout.split('Password: ')[1] | default(root_password_out.stdout) }}"
  tags: gitlab_post
